# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  admin_name: Admin
  admin_email: hello@localhost:3000
  admin_password: 123123
  domain_name: hello@localhost:3000
  secret_key_base: 4ba810fcf986683dc4bba8b09cc3534a373cea0f45674a7489bd4a9c89b99b6ceb90e3426639b8092b64b5035da21954ab575cf2de3b69a4927dae00bdb0e8c9

test:
  domain_name: hello@localhost:3000
  secret_key_base: a0a672191ea08a00bd883556869042129af150d2ea2085c123029407deab2c5e737e4e3a329a0fceed2ed0bb2796d85e4a4da8309114d671665301220ec5f8cb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  admin_name: Admin
  admin_email: admin@travlendarplus.heroku.com
  admin_password: 123123
  domain_name: travlendarplus.heroku.com
  secret_key_base: 4ba810fcf986683dc4bba8b09cc3534a373cea0f45674a7489bd4a9c89b99b6ceb90e3426639b8092b64b5035da21954ab575cf2de3b69a4927dae00bdb0e8c9
